all:
  vars:
    java_home: /usr/local/openjdk-8
    nio_jar: nio-node.jar
  children:
    readers:
      hosts:
        reader_1:
          ansible_host: localhost
          ansible_port: 4422
          nio_host: reader
          nio_port: 51700
    writers:
      hosts:
        writer_1:
          ansible_host: localhost
          ansible_port: 5522
